version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db

  load_balancer:
    build:
      context: ./src
      dockerfile: Dockerfile # Dockerfile for the load balancer
    ports:
      - "5000:5000"
    depends_on:
      - web_server1
      - web_server2
      - web_server3

  web_server1:
    build:
      context: ./src
      dockerfile: Dockerfile.server # Dockerfile for the server
    environment:
      - SERVER_ID=1

  web_server2:
    build:
      context: ./src
      dockerfile: Dockerfile.server # Dockerfile for the server
    environment:
      - SERVER_ID=2

  web_server3:
    build:
      context: ./src
      dockerfile: Dockerfile.server # Dockerfile for the server
    environment:
      - SERVER_ID=3
